services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - static_volume:/home/rdmo/rdmo-app/static_root
      - vendor_volume:/home/rdmo/rdmo-app/vendor
    expose:
     - 8000
    env_file:
      - dev.env
    depends_on:
      db:
        condition: service_healthy
        restart: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-rdmo.rule=Host(`dev-rdmo.localhost`)"

  db: # defaults to sqlite
    image: "postgres:17"
    restart: always
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - dev.env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 2s
      timeout: 5s
      retries: 10

  traefik:
    image: traefik:v3.3.3
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      - "./traefik/traefik.test.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  pgdata:
  static_volume:
  vendor_volume: